### ISSUE TITLE
`CALL_REF` and friends take `typeuse` instead of `typeidx`

### ISSUE THREAD

**Issue by tlively** [Wasm-DSL/spectec#96]
It seems odd that `CALL_REF`, `CALL_INDIRECT`, `RETURN_CALL_REF` and `RETURN_CALL_INDIRECT` take `typeuse` instead of `typeidx` for their immediates. In contrast, all of the struct and array instructions take `typeidx`, which seems to more precisely describe their syntax. Is this something that can be cleaned up?

**Comment by rossberg** [comment]
Yeah, CALL_REF and friends need the more general typeuse because they can arise on the r.h.s. of a reduction where we may not have a suitable type index that is locally valid. The other instructions do not ever occur on the r.h.s. in such a way, so the same generalisation wasn't necessary, though I considered it. I don't feel strongly, typeuse makes things a bit more cumbersome.

**Comment by tlively** [comment]
Using typeuse where necessary and type idk where possible makes sense to me. Thanks!
